name: build

on:
  push:
    branches-ignore:
      - continuous

jobs:
  build-and-upload:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get Emacs release version
        run: |
          RELEASE_VERSION=$(wget -q "https://ftp.gnu.org/pub/gnu/emacs/?C=M;O=D" -O - | grep -oe ">emacs-.*tar.gz" | head -n 1 | cut -d - -f 2 | sed -e 's|.tar.gz||g')
          echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV

      - name: Download and extract Emacs
        run: |
          wget -c "http://ftpmirror.gnu.org/emacs/emacs-${RELEASE_VERSION}.tar.gz"
          tar xf emacs-*tar.gz
          cd emacs*

      - name: Install dependencies
        run: |
          sudo apt-get build-dep emacs24
          sudo apt-get -y install libgtk-3-dev libwebkitgtk-3.0-dev

      - name: Configure and build Emacs
        run: |
          ./autogen.sh
          ./configure --prefix=/app --without-selinux --with-x-toolkit=gtk3
          make -j$(nproc)
          sudo make install
          cd ..

      - name: Create AppImage
        run: bash -ex appimage.sh

      - name: Upload AppImage
        run: |
          readlink -f .
          wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
          bash upload.sh ../../../out/*.AppImage*
